sudo: false
language: rust
matrix:
  include:
    # Linux
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=i586-unknown-linux-gnu

    # iOS
    - env: TARGET=aarch64-apple-ios DISABLE_TESTS=1
      os: osx
#   - env: TARGET=armv7-apple-ios DISABLE_TESTS=1
#     os: osx
#   - env: TARGET=armv7s-apple-ios DISABLE_TESTS=1
#     os: osx
#   - env: TARGET=i386-apple-ios DISABLE_TESTS=1
#     os: osx
#   - env: TARGET=x86_64-apple-ios DISABLE_TESTS=1
#     os: osx

#   # OSX
#   - env: TARGET=i686-apple-darwin
#     os: osx
#   - env: TARGET=x86_64-apple-darwin
#     os: osx

#   # New Architectures
    - env: TARGET=arm-unknown-linux-gnueabi DISABLE_TESTS=1
    - env: TARGET=armv7-unknown-linux-gnueabihf
#   - env: TARGET=sparc64-unknown-linux-gnu DISABLE_TESTS=1

#   # arm
#   - env: TARGET=arm-unknown-linux-musleabi DISABLE_TESTS=1
#   - env: TARGET=armv7-unknown-linux-musleabihf DISABLE_TESTS=1
#   - env: TARGET=i586-unknown-linux-musl
#   - env: TARGET=armv5te-unknown-linux-gnueabi

#   # *BSD
#   - env: TARGET=i686-unknown-freebsd DISABLE_TESTS=1
#   - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
#   - env: TARGET=x86_64-unknown-netbsd DISABLE_TESTS=1

#   # Other architectures
#   - env: TARGET=aarch64-unknown-linux-gnu
#   - env: TARGET=mips-unknown-linux-gnu
#   - env: TARGET=mips64-unknown-linux-gnuabi64
#   - env: TARGET=mips64el-unknown-linux-gnuabi64
#   - env: TARGET=mipsel-unknown-linux-gnu
#   - env: TARGET=powerpc-unknown-linux-gnu DISABLE_TESTS=1
#   - env: TARGET=powerpc64-unknown-linux-gnu
#   - env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1

#   # Will probably fail due to LLVM 6
#   - env: TARGET=powerpc64le-unknown-linux-gnu

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: beta
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: beta
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

before_install:
  - set -e
  - rustup self update

install:
- |
  case $TARGET in
      aarch64-apple-ios)
          rustup target install $TARGET
          ;;
      armv7-apple-ios)
          rustup target install $TARGET
          ;;
      armv7s-apple-ios)
          rustup target install $TARGET
          ;;
      i386-apple-ios)
          rustup target install $TARGET
          ;;
      x86_64-apple-ios)
          rustup target install $TARGET
          ;;
      wasm32-unknown-unknown)
          rustup target install $TARGET
          ;;
      x86_64-unknown-linux-gnux32)
          rustup target install $TARGET
          ;;
      i586-unknown-linux-musl)
          rustup target install $TARGET
          ;;
      armv5te-unknown-linux-gnueabi)
          rustup target install $TARGET
          ;;
  esac
  source ~/.cargo/env || true

script:
- |
  cargo build --target "$TARGET" --features yaml_enc,bin_enc,ron_enc
  [[ $DISABLE_TESTS -eq 0 ]] && cargo test --target "$TARGET" --features yaml_enc,bin_enc,ron_enc
  cargo doc --target "$TARGET" --features yaml_enc,bin_enc,ron_enc

env:
  global:
  - secure: RFX1Ke3uk8ZdrAGwKPP7FXqQfC6bkGMDzV5ut9s5da6ClvoafosJF4RBvXi5j8KhQP9Kyow7Z8IwtTExNHMIjlE0MguHsYdFBdkj9HdjrqBQHThx5vMOq3VY3bNq9ah83Q6idoTTpQvoZ380BSHznHz8E3rmKGbEA0Z1NigWlT8DFfgqI5nTa64/bvD8IzMTjkLax4pq1SjsG8v+UgwNxkuYE6Yl/mpQJ/xTCGYiFHLKk4EW8z2I5DcK/XqY+w42uFDP2BRvXdzuS937A0lGZtAiK3sKJCBDq/2Ulkz4+onkAo9QT0k9Eea9dSoxXDk3RJHzDb5wLANtubxAWyTKiyTlO3I81ogPmHevSv3xDXXwLBjPxwwIRI1qt/01Nod4yIT4fWfIxcW+rY/W5P4v5QbvAJ079v8be1lnwCEFP55WXfTFEypvKUmNpCTeY9nAKiLywpQuibi/TuHmVH+R9xWlJaXrJ8+fM+dkl57V7AnIKs3nnYmE/c5guUakJ46QVZZtSQRcFfD0QeZPM5WaqAjiZ52eP4y/Mi5Rjg4/noLjXoR3YWYxWZsT5b7U2hv/wEMTzERgHev3aPZttO7gr3ug/FDv0TP6PKPCLd/i+g0w4RKRGArcAXIBWHdeEhfOYuC8Q93gl3d/qutvgGdWF4sdBpaPRcwmaWD+FoEWjWQ=
